on:
  push:
    tags:
      - 'v*'
name: Deploy Wiki
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm i -g serverless
    - run: npm i
      working-directory: ./packages/wiki
    - run: sls
      working-directory: ./packages/wiki
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
